version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username"
    assignees:
      - "your-github-username"
    commit-message:
      prefix: "feat"
      prefix-development: "chore"
      include: "scope"


  - package-ecosystem: "gitsubmodule"
    directory: "/contracts"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
